# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f02ad8313c5efada0e03309a0631496f0596027167aed54f62b3711ed21c83e10baa5451834e40e8881f2dbbc24ad4a1a79c8cf18016464b179a2ee66c054b77

test:
  secret_key_base: 087795ba9cab9e631ea8a2bec5d7d0e83bb29902142e18f730e5c2c566d9e07608f7b29dd2f493322070785427baeae942717e8c1865409f1549c02bb88bb0eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
